# Site
name: "CARPE DIEM"
description: Huan's Blog
logo: assets/images/logo.png
favicon: assets/images/shipfail-icon.svg
url: https://huan.github.io
baseurl:
email: huan@chatie.io
mailchimp-list: https://zixia.us4.list-manage.com/subscribe/post?u=a8584b55dea5aa8bbc14bd1a0&amp;id=d9899f0d70

math:
  enable_by_default: false

mermaid:
  enable_by_default: false

include: ["_pages"]
permalink: blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: _posts
    values:
      layout: post
      comments: true
      author: Huan
      avatar: /assets/authors/huan/avatar.webp

  # all pages
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _authors
    values:
      layout: author
      comments: true
      search: false

# Syntax
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax

# Paginate
paginate: 15
paginate_path: /blog/page:num/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  - package.json
  - _site
  - node_modules

collections:
  authors:
    output: true
    permalink: /:collection/:path/
